### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load (using webtrees 2.0.2)

### ISSUE THREAD

**Issue by hartenthaler** [ric2016/gov4webtrees#14]
on [http://ahnen2.hartenthaler.eu/index.php?route=%2Ftree%2Fahnen%2Findividual%2FI8860%2FChristine%2520Hinterh%25C3%25B6lzl](http://ahnen2.hartenthaler.eu/index.php?route=%2Ftree%2Fahnen%2Findividual%2FI8860%2FChristine%2520Hinterh%25C3%25B6lzl)
there is an error:
SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://gov.genealogy.net/services/ComplexService?wsdl' : failed to load external entity "http://gov.genealogy.net/services/ComplexService?wsdl"
 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php:72
#0 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(72): SoapClient->SoapClient()
....
GEDCOM for this person contains:
```
1 BIRT
2 DATE 23 JAN 1932
2 PLAC Lanzendorf bei Kasten; Kasten bei Böheimkirchen, St. Pölten-Land, Niederösterreich, AUT
3 _GOV LANTENJN78VD
```

The same error is on http://ahnen2.hartenthaler.eu/index.php?route=%2Ftree%2Fahnen%2Findividual%2FI3642%2FMaria%2520Goiser
but other persons are ok.

**Comment by ric2016** [comment]
I will try to reproduce this.
As a workaround, try switching to nusoap (in the module configuration) - does that work?

**Comment by hartenthaler** [comment]
No, but the error message is different:
```
First parameter must either be an object or the name of an existing class …/modules_v4/vesta_gov4webtrees/FunctionsGov.php:672
#0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(672): property_exists()
#2 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(500): Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::loadGovObject()
#3 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(451): 
```

**Comment by ric2016** [comment]
> other persons are ok

That's likely only because all data is already availabe locally on your server. Reloading any GOV-Id will probably result in the same error.

I guess the different nusoap error just indicates that the nusoap client doesn't work properly either on your server.
Did this use to work on your server at all without errors?
Have you changed your php version, or any other server settings?
You'll probably have to debug the SOAP requests yourself, I'm not sure how to handle this otherwise. You could try loading the wsdl file directly, via

```
try {
  $file = file_get_contents($wsdl);
  error_log("wsdl loaded: ".$file);
} catch (\Exception $ex) {
  error_log("wsdl NOT loaded: ".$ex->getTraceAsString());
}
```

And check if that works.

Elsewhere on the web it is suggested to set
`libxml_disable_entity_loader(false);`
prior to loading the wsdl, does that make any difference?

**Comment by hartenthaler** [comment]
The errors disappeared! I'm using your module for many months and had never seen these error messages before. There was no change in my server configuration in the last weeks, as far as I know. Today I added some _GOV GEDCOM tags without an error, so I tried the two persons with the error again: without any change, there is no error anymore. Problem solved!?

**Comment by ric2016** [comment]
Maybe there was some kind of temporary network-related issue between your server and the GOV server.

Until that reappears, we cannot and don't have to do anything.
